server:
  port: 8080
  servlet:
    context-path: /weconnect

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/weconnectdb?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never

  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

app:
  file:
    storage-dir: D:/upload
    dowload-prefix: http://localhost:8080/identity/media/

  cors-origin: http://localhost:5173
jwt:
  valid-duration: 3600
  refresh-duration: 360000
  signerKey: "/fVsiuXso0XANi6In?w8CiF!zf0qQ6DdC6vvpfw?tdstg?YisbW0/ZEJ8VoUuE4jrRg?048UV3tD4LZnH7EUoYppt4J943NMrA64YoCMib6tlcIG2k5QF/9hhrGc!EprxtCdJhqkdIi6xis0MwrJyopN0cXRPPFcZq6gwMnpuekDCYR8wEqEXfFgWS-Urd?v=Q60!WohGE48T3FQESZPDzqJnPp2xFUCPQiUvWeCHyGJ64q=7xYLVPNQMhQJub98"